-- ==========================================
-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS
-- COPIE TODO ESTE CÓDIGO E COLE NO SQL EDITOR DO SUPABASE
-- ==========================================

-- 1. TABELA DE USUÁRIOS
-- Armazena dados de alunos e coordenação
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY, -- ID vinculado ao Auth do Supabase
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    tipo TEXT DEFAULT 'student', -- 'student' (aluno) ou 'teacher' (coordenação)
    curso TEXT,
    grade TEXT,
    avatar_url TEXT,
    notas JSONB DEFAULT '{}'::jsonb, -- Armazena as notas de todas as matérias
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABELA DE MENSAGENS (MURAL)
-- Armazena o chat e os arquivos enviados
CREATE TABLE IF NOT EXISTS public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT,
    usuario_nome TEXT NOT NULL,
    usuario_email TEXT,
    turma_id TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    arquivo_url TEXT, -- Link do arquivo no Storage
    arquivo_nome TEXT,
    arquivo_tipo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. SEGURANÇA (POLICIES)
-- Permite que todos os usuários logados leiam e escrevam
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;

-- Políticas para Usuários
CREATE POLICY "Usuários podem ver todos os perfis" ON public.usuarios FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuários podem atualizar seus próprios perfis" ON public.usuarios FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Inserção automática via App" ON public.usuarios FOR INSERT TO authenticated WITH CHECK (true);

-- Políticas para Mensagens
CREATE POLICY "Mensagens visíveis para todos logados" ON public.mensagens FOR SELECT TO authenticated USING (true);
CREATE POLICY "Qualquer logado pode enviar mensagens" ON public.mensagens FOR INSERT TO authenticated WITH CHECK (true);

-- 4. BUCKET DE ARQUIVOS (STORAGE)
-- IMPORTANTE: Você deve criar manualmente um bucket chamado 'arquivos_turma' 
-- na aba 'Storage' do Supabase e marcar como 'Public'.
