-- ========================================================
-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS - PORTAL CETEP
-- COLE ESTE CÓDIGO NO 'SQL EDITOR' DO SEU SUPABASE
-- ========================================================

-- 1. TABELA DE USUÁRIOS
-- Esta tabela armazena os dados de alunos e da coordenação.
-- Quando alguém faz login pela primeira vez, o site salva os dados aqui.
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY, -- Identificador único do Supabase Auth
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    tipo TEXT DEFAULT 'student', -- 'student' (aluno) ou 'teacher' (coordenação)
    curso TEXT DEFAULT 'Técnico em Informática',
    grade TEXT DEFAULT '1º Ano',
    avatar_url TEXT,
    notas JSONB DEFAULT '{}'::jsonb, -- Notas em formato JSON: {"Materia": {"n1": 10, "n2": 8}}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABELA DE MENSAGENS (MURAL)
-- Esta tabela armazena as mensagens do chat e os arquivos enviados.
CREATE TABLE IF NOT EXISTS public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT,
    usuario_nome TEXT NOT NULL,
    usuario_email TEXT NOT NULL,
    turma_id TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    arquivo_url TEXT,
    arquivo_nome TEXT,
    arquivo_tipo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. HABILITAR SEGURANÇA (RLS)
-- Isso protege seus dados contra invasores.
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;

-- 4. POLÍTICAS DE ACESSO
-- Define quem pode ler e escrever os dados.

-- USUÁRIOS: Permite leitura para todos logados e escrita para o próprio dono.
DROP POLICY IF EXISTS "Acesso Publico Usuarios" ON public.usuarios;
CREATE POLICY "Acesso Publico Usuarios" ON public.usuarios FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Update Proprio Usuario" ON public.usuarios;
CREATE POLICY "Update Proprio Usuario" ON public.usuarios FOR UPDATE TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Insert via Registro" ON public.usuarios;
CREATE POLICY "Insert via Registro" ON public.usuarios FOR INSERT TO authenticated WITH CHECK (true);

-- MENSAGENS: Permite leitura e envio para todos os usuários autenticados.
DROP POLICY IF EXISTS "Leitura Mural" ON public.mensagens;
CREATE POLICY "Leitura Mural" ON public.mensagens FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Envio Mural" ON public.mensagens;
CREATE POLICY "Envio Mural" ON public.mensagens FOR INSERT TO authenticated WITH CHECK (true);

-- ========================================================
-- PASSO ADICIONAL: STORAGE (ARQUIVOS)
-- 1. No Supabase, vá na aba 'Storage' (ícone de caixa) à esquerda.
-- 2. Clique em 'New Bucket'.
-- 3. Nome exato: arquivos_turma
-- 4. Marque a opção 'Public bucket'.
-- 5. Clique em 'Save'.
-- ========================================================
