-- EXECUTAR ESTE SCRIPT NO EDITOR SQL DO SUPABASE
-- Para corrigir o erro da tabela "mensagens" e garantir que todos os usuários apareçam.

-- 1. Tabela de Usuários (se ainda não existir com esta estrutura)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    tipo TEXT DEFAULT 'student', -- 'student' ou 'teacher'
    curso TEXT,
    grade TEXT,
    notas JSONB DEFAULT '{}'::jsonb,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabela de Mensagens do Mural
CREATE TABLE IF NOT EXISTS public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT,
    usuario_nome TEXT NOT NULL,
    usuario_email TEXT,
    turma_id TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    arquivo_url TEXT,
    arquivo_nome TEXT,
    arquivo_tipo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Habilitar Log para todos verem as mensagens (opcional, dependendo da sua segurança)
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Mensagens visíveis para todos os autenticados" ON public.mensagens 
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "Mensagens inseríveis por todos os autenticados" ON public.mensagens 
    FOR INSERT TO authenticated WITH CHECK (true);

-- 4. Criar o Bucket de Armazenamento para Arquivos (Manualmente no Dashboard do Supabase)
-- Lembre-se de criar um bucket chamado 'arquivos_turma' com acesso público no menu Storage.
